<#
 Official ComfyUI portable (NVIDIA, CUDA 13.0, Python 3.13) -> <ROOT>\COMFYUI
   download : @Runtime\downloads\ComfyUI_windows_portable_nvidia.7z   (resumable, kept afterwards)
   extractor: @Runtime\downloads\7zr.exe (official standalone 7-Zip console, downloaded from 7-zip.org)
   result   : COMFYUI\{ComfyUI, python_embeded, update, run_nvidia_gpu.bat, ...}
 Windows PowerShell 5.1 compatible.
   powershell -ExecutionPolicy Bypass -File Install_ComfyUI.ps1 [-Force]
#>
param([switch]$Force)
$ErrorActionPreference = "Stop"
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
$Here   = Split-Path -Parent $MyInvocation.MyCommand.Definition
$Root   = (Resolve-Path (Join-Path $Here "..")).Path
$Down   = Join-Path $Root "@Runtime\downloads"
$Target = Join-Path $Root "COMFYUI"
$Tmp    = Join-Path $Root "COMFYUI__extract"
$Url    = "https://github.com/Comfy-Org/ComfyUI/releases/latest/download/ComfyUI_windows_portable_nvidia.7z"
$Arc    = Join-Path $Down "ComfyUI_windows_portable_nvidia.7z"
$SevenZ = Join-Path $Down "7zr.exe"
New-Item -ItemType Directory -Force -Path $Down | Out-Null

if ((Test-Path (Join-Path $Target "python_embeded\python.exe")) -and -not $Force) {
    Write-Host "ComfyUI already installed in $Target (use -Force to redo)." -ForegroundColor Green; exit 0
}
$ArcName = "ComfyUI_windows_portable_nvidia.7z"
if ((Test-Path $Target) -and -not $Force) {
    $others = Get-ChildItem -LiteralPath $Target -Force | Where-Object { $_.Name -notlike "ComfyUI_windows_portable_nvidia*" }
    if ($others) { throw "Target exists and is not empty: $Target - move it away or run with -Force" }
}

Write-Host "`n[1/5] 7-Zip console (7zr.exe)" -ForegroundColor Cyan
if (-not (Test-Path $SevenZ)) {
    & curl.exe -L --fail --retry 3 -o $SevenZ "https://www.7-zip.org/a/7zr.exe"
    if ($LASTEXITCODE -ne 0) { throw "7zr.exe download failed" }
}

Write-Host "`n[2/5] ComfyUI portable archive" -ForegroundColor Cyan
# an archive you downloaded by hand is used as is: COMFYUI\ (root of the target), <ROOT>\, or @Runtime\downloads\
$Manual = @((Join-Path $Target $ArcName), (Join-Path $Root $ArcName)) | Where-Object { Test-Path $_ } | Select-Object -First 1
if ($Manual) {
    $Arc = $Manual
    Write-Host "Using archive: $Arc"
} else {
    Write-Host "Download (large, resumable) ..."
    & curl.exe -L --fail --retry 5 --retry-delay 5 -C - -o $Arc $Url
    if ($LASTEXITCODE -ne 0) { throw "download failed (curl exit $LASTEXITCODE) - run again, it resumes" }
}
if (Get-ChildItem -LiteralPath (Split-Path $Arc) -Filter "*.crdownload" -ErrorAction SilentlyContinue | Where-Object { $_.Name -like "*ComfyUI*" }) {
    throw "An unfinished browser download (.crdownload) is next to the archive - wait until it is complete."
}
Write-Host ("Archive: {0:N0} MB" -f ((Get-Item $Arc).Length / 1MB))

Write-Host "`n[3/5] Extract" -ForegroundColor Cyan
if (Test-Path $Tmp) { Remove-Item -LiteralPath $Tmp -Recurse -Force }
New-Item -ItemType Directory -Force -Path $Tmp | Out-Null
& $SevenZ x $Arc "-o$Tmp" -y
if ($LASTEXITCODE -ne 0) { throw "extraction failed (7zr exit $LASTEXITCODE) - archive may be incomplete: delete $Arc and run again" }

Write-Host "`n[4/5] Move into $Target" -ForegroundColor Cyan
$Inner = Join-Path $Tmp "ComfyUI_windows_portable"
if (-not (Test-Path $Inner)) { $Inner = $Tmp }
New-Item -ItemType Directory -Force -Path $Target | Out-Null
Get-ChildItem -LiteralPath $Inner -Force | ForEach-Object { Move-Item -LiteralPath $_.FullName -Destination $Target -Force }
Remove-Item -LiteralPath $Tmp -Recurse -Force -ErrorAction SilentlyContinue

if (-not (Test-Path (Join-Path $Target "python_embeded\python.exe"))) { throw "python_embeded missing after extraction - check $Target" }

# ---- adaptations for this portable workspace ---------------------------------------------
Write-Host "`n[5/5] Workspace adaptations" -ForegroundColor Cyan
$Py = Join-Path $Target "python_embeded\python.exe"
foreach ($d in "cache\huggingface", "cache\torch") { New-Item -ItemType Directory -Force -Path (Join-Path $Target $d) | Out-Null }
$ManReq = Join-Path $Target "ComfyUI\manager_requirements.txt"
if (Test-Path $ManReq) {
    Write-Host "ComfyUI-Manager requirements ..."
    & $Py -s -m pip install -r $ManReq --no-warn-script-location
    if ($LASTEXITCODE -ne 0) { Write-Warning "Manager requirements failed (ComfyUI still works, launcher then starts without --enable-manager)" }
} else { Write-Warning "manager_requirements.txt not found - Manager not enabled" }
# models: extra_model_paths.yaml is generated by the AI_Launcher on every ComfyUI start (central AI_Modells library)
if ($Arc -like "$Target*") {
    try { Move-Item -LiteralPath $Arc -Destination (Join-Path $Down $ArcName) -Force; $Arc = Join-Path $Down $ArcName } catch { Write-Warning "Could not move the archive out of $Target" }
}
Write-Host "`nDone: $Target" -ForegroundColor Green
Write-Host "Archive kept: $Arc (delete it to free space)."
