"""Tool modules. A module knows how to check itself, prepare, and build its start command.

Adding a tool = add a class here (or an entry in config.json -> custom_tools).
"""
from __future__ import annotations

import os
from dataclasses import dataclass, field
from urllib.parse import urlparse
from pathlib import Path

from . import mcp, profiles, provider, runtime_tools
from .config import Config

EXTRA_MODELS_TEMPLATE = """# Generated by AI_Launcher on every ComfyUI start - do not edit (edit config.json instead).
aimodels:
    base_path: {base}/
    checkpoints: |
        checkpoints
        safetensors
    loras: |
        loras
        safetensors
    vae: vae
    embeddings: embeddings
    upscale_models: upscale_models
    controlnet: controlnet
    clip: clip
    clip_vision: clip_vision
    ipadapter: ipadapter
    facerestore_models: facerestore_models
    gligen: gligen
    hypernetworks: hypernetworks
    text_encoders: |
        text_encoders
        safetensors
    diffusion_models: |
        diffusion_models
        unet
        safetensors
        gguf
    unet: |
        unet
        gguf
    LLM: LLM
"""


@dataclass
class StartSpec:
    cmd: list[str]
    cwd: str | None = None
    env: dict[str, str] = field(default_factory=dict)


class Module:
    id = ""
    name = ""
    external = False      # True = runs on another machine, monitor only
    interactive = False   # True = needs a real console window (interactive CLI); else output goes to a Processes tab
    host = "127.0.0.1"
    health_path: str | None = None    # HTTP path that answers 200 only when the service is really ready (None = open port is enough)
    # "local"     = model/inference runs on this PC's own GPU/CPU (ComfyUI, Ollama, llama.cpp, Scrapling)
    # "api"       = CLI tool that talks to a remote provider's cloud API for its model
    # "local-off" = CLI tool switched to "local" (see core/provider.py) but no local server answers right now
    # "cloud"     = an always-on service reachable over the network but not running on this PC (ExternalModule)
    # ""          = unknown / not applicable - no badge shown
    _backend_kind = ""

    def __init__(self, cfg: Config):
        self.cfg = cfg

    def backend_kind(self) -> str:
        """'local' | 'api' | 'cloud' | '' - drives the Dashboard's Local/Cloud/API badge."""
        return self._backend_kind

    def port(self) -> int | None:
        return None

    def url(self) -> str | None:
        return None

    def check(self) -> tuple[bool, str]:
        raise NotImplementedError

    def prepare(self) -> list[str]:
        """Run before start; returns log lines."""
        return []

    def build(self) -> StartSpec:
        raise NotImplementedError

    def version(self) -> str:
        return ""

    def update_options(self) -> dict[str, StartSpec]:
        """Named update commands (label -> command), run in their own console. Empty = no update support."""
        return {}


class ComfyUIModule(Module):
    id = "comfyui"
    name = "ComfyUI"
    health_path = "/system_stats"
    _backend_kind = "local"

    def port(self):
        return self.cfg.port("comfyui")

    def url(self):
        return f"http://127.0.0.1:{self.port()}"

    def _layout(self, root: Path) -> str:
        """'bat' = own ComfyUI.bat launcher, 'official' = Comfy-Org portable (python_embeded + ComfyUI\\main.py)."""
        if (root / "ComfyUI.bat").is_file():
            return "bat"
        if (root / "python_embeded" / "python.exe").is_file() and (root / "ComfyUI" / "main.py").is_file():
            return "official"
        return ""

    def check(self):
        root = self.cfg.path("comfyui")
        if not root.is_dir():
            return False, f"folder not found: {root} - extract ComfyUI_windows_portable_nvidia.7z there"
        if not self._layout(root):
            return False, f"no ComfyUI found in {root} (need python_embeded + ComfyUI\\main.py, or ComfyUI.bat)"
        return True, "ready"

    def prepare(self):
        models = self.cfg.path("models")
        yaml = self.cfg.path("comfyui") / "config" / "extra_model_paths.yaml"
        yaml.parent.mkdir(parents=True, exist_ok=True)
        yaml.write_text(EXTRA_MODELS_TEMPLATE.format(base=str(models).replace("\\", "/")), encoding="utf-8")
        msg = [f"extra_model_paths.yaml written -> models: {models}"]
        if not models.exists():
            msg.append(f"WARNING: model folder does not exist: {models}")
        return msg

    def build(self):
        root = self.cfg.path("comfyui")
        args = ["--listen", self.cfg.host(), "--port", str(self.port())]
        if self._layout(root) == "bat":
            return StartSpec([str(root / "ComfyUI.bat"), *args], cwd=str(root))
        # official portable: same command as run_nvidia_gpu.bat, adapted to this portable workspace
        py = root / "python_embeded" / "python.exe"
        yaml = root / "config" / "extra_model_paths.yaml"        # written by prepare(); the official package does not read it on its own
        cmd = [str(py), "-s", str(root / "ComfyUI" / "main.py"), "--windows-standalone-build",
               "--extra-model-paths-config", str(yaml),
               "--disable-auto-launch",                            # the dashboard has an Open button
               "--disable-dynamic-vram",                           # DynamicVRAM (comfy-aimdo) off, see Start.bat
               *args]
        if self._manager_installed(root):
            cmd.append("--enable-manager")
        cache = root / "cache"                                     # keep HF / torch downloads on the stick, not in C:\Users\...
        env = {"HF_HOME": str(cache / "huggingface"), "TORCH_HOME": str(cache / "torch"), "PYTHONUTF8": "1"}
        env.update(runtime_tools.tool_env(self.cfg))                # portable ExifTool / FFmpeg for video + metadata nodes
        return StartSpec(cmd, cwd=str(root), env=env)

    @staticmethod
    def _manager_installed(root: Path) -> bool:
        sp = root / "python_embeded" / "Lib" / "site-packages"
        return sp.is_dir() and any(sp.glob("comfyui_manager*"))

    def version(self):
        f = self.cfg.path("comfyui") / "ComfyUI" / "comfyui_version.py"
        try:
            for line in f.read_text(encoding="utf-8").splitlines():
                if line.startswith("__version__"):
                    return line.split("=", 1)[1].strip().strip("\"'")
        except OSError:
            pass
        return ""

    def update_options(self):
        """Own updater (Update_ComfyUI.ps1): backup + torch/CUDA stack pinned via constraints + rollback info.
        The official update\\*.bat are not offered - 'update_comfyui_and_python_dependencies' can replace torch."""
        root = self.cfg.path("comfyui")
        script = self.cfg.path("runtime").parent / "AI_Launcher" / "Update_ComfyUI.ps1"
        if not script.is_file() or not (root / "update" / "update.py").is_file():
            return {}
        base = ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(script),
                "-Root", str(root), "-Port", str(self.port())]
        return {"ComfyUI (latest, keeps torch)": StartSpec(base, cwd=str(root)),
                "ComfyUI (stable release, keeps torch)": StartSpec(base + ["-Stable"], cwd=str(root))}


class OllamaModule(Module):
    id = "ollama"
    name = "Ollama"
    health_path = "/api/version"
    _backend_kind = "local"

    def port(self):
        return self.cfg.port("ollama")

    def _exe(self) -> Path | None:
        root = self.cfg.path("ollama")
        for rel in ("bin/ollama.exe", "ollama.exe", "app/ollama/ollama.exe", "ollama"):
            if (root / rel).is_file():
                return root / rel
        if root.is_dir():
            for i, p in enumerate(root.rglob("ollama.exe")):
                return p
        return None

    def check(self):
        exe = self._exe()
        return (True, str(exe)) if exe else (False, f"ollama.exe not found below {self.cfg.path('ollama')}")

    def prepare(self):
        self.cfg.path("ollama_models").mkdir(parents=True, exist_ok=True)
        return [f"OLLAMA_MODELS = {self.cfg.path('ollama_models')}"]

    def build(self):
        exe = self._exe()
        env = {"OLLAMA_MODELS": str(self.cfg.path("ollama_models")),
               "OLLAMA_HOST": f"{self.cfg.host()}:{self.port()}"}
        from .tuning import ollama_env          # server-level tuning (Tuning page): context, KV type, slots
        env.update(ollama_env(self.cfg.data.get("ollama", {}) or {}))
        return StartSpec([str(exe), "serve"], cwd=str(exe.parent), env=env)


class LlamaCppModule(Module):
    """llama.cpp llama-server: serves GGUF files straight from the model library (no import needed)."""
    id = "llamacpp"
    name = "llama.cpp server"
    health_path = "/health"          # 503 while the model is loading, 200 {"status":"ok"} when ready
    _backend_kind = "local"

    def port(self):
        return self.cfg.port("llamacpp")

    def url(self):
        return f"http://127.0.0.1:{self.port()}"

    def _exe(self) -> Path:
        return self.cfg.path("llamacpp") / "bin" / "llama-server.exe"

    def _opts(self) -> dict:
        return {"model": "", "ctx": 8192, "ngl": "auto", **self.cfg.data.get("llamacpp", {})}

    def _model(self) -> Path:
        """model = absolute path, or relative to the GGUF folder, or relative to the model library root."""
        m = str(self._opts()["model"])
        cands = [Path(m), self.cfg.path("gguf") / m, self.cfg.path("models") / m]
        for c in cands:
            if c.is_file():
                return c
        return cands[1]

    def check(self):
        if not self._exe().is_file():
            return False, "llama-server.exe missing - run install_llamacpp.bat in AI_Ollama_CCP"
        if not self._opts()["model"] or not self._model().is_file():
            return False, f"model not found: {self._model()} (set it in config.json -> llamacpp.model)"
        return True, "ready"

    def build(self):
        o = self._opts()
        cmd = [str(self._exe()), "-m", str(self._model()), "-c", str(o["ctx"])]
        if str(o["ngl"]).strip().lower() not in ("", "auto"):
            cmd += ["-ngl", str(o["ngl"])]       # explicit layer count; "auto" = llama.cpp fits it to the free VRAM
        cmd += ["--flash-attn", "on", "--host", self.cfg.host(), "--port", str(self.port())]
        from .tuning import llamacpp_extra_args  # KV type / batch / slots set on the Tuning page
        cmd += ["--metrics"]                       # Prometheus /metrics: live request counters for the Tuning page
        cmd += llamacpp_extra_args(self.cfg.data.get("llamacpp", {}) or {})
        return StartSpec(cmd, cwd=str(self._exe().parent))

    def version(self):
        v = self.cfg.path("llamacpp") / "VERSION.txt"
        try:
            return v.read_text(encoding="utf-8").strip()
        except OSError:
            return ""

    def update_options(self):
        s = self.cfg.path("llamacpp") / "install_llamacpp.ps1"
        if not s.is_file():
            return {}
        return {"llama.cpp (re-run installer)": StartSpec(
            ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(s)], cwd=str(s.parent))}


class _ScraplingBase(Module):
    """Scrapling lives in <ROOT>/AI_Scrapling: packages in site-packages\\, browsers in browsers\\.
    It runs on the shared @Runtime python (no venv); everything is wired through env vars, nothing is global."""

    def _dir(self) -> Path:
        return self.cfg.path("scrapling")

    def _py(self) -> Path:
        return self.cfg.path("runtime") / "python" / "python.exe"

    def check(self):
        d = self._dir()
        if not self._py().is_file():
            return False, "shared runtime missing - run Setup_Runtime.bat first"
        if not (d / "site-packages" / "scrapling").is_dir():
            return False, f"Scrapling not installed - run {d}\\Install_Scrapling.bat"
        return True, "ready"

    def _env(self) -> dict[str, str]:
        d = self._dir()
        home = d / "home"
        return {
            "PYTHONPATH": str(d / "site-packages"),
            "PLAYWRIGHT_BROWSERS_PATH": str(d / "browsers"),
            "LOCALAPPDATA": str(home / "AppData" / "Local"),     # camoufox cache stays on the stick
            "PYTHONUTF8": "1",
            "PYTHONIOENCODING": "utf-8",
        }

    def _cli(self, *args: str) -> list[str]:
        return [str(self._py()), str(self._dir() / "scrapling_cli.py"), *args]

    def version(self):
        for p in (self._dir() / "site-packages").glob("scrapling-*.dist-info"):
            return p.name[len("scrapling-"):-len(".dist-info")]
        return ""

    def update_options(self):
        s = self._dir() / "Install_Scrapling.ps1"
        if not s.is_file():
            return {}
        label = "Scrapling (upgrade)" if self.check()[0] else "Scrapling (install)"
        return {label: StartSpec(
            ["powershell.exe", "-NoProfile", "-ExecutionPolicy", "Bypass", "-File", str(s), "-Upgrade"], cwd=str(s.parent))}


class ScraplingMcpModule(_ScraplingBase):
    """Scrapling MCP server (streamable-http) for Claude / Codex / OpenWebUI. URL: http://host:port/mcp"""
    id = "scrapling"
    name = "Scrapling MCP server"
    _backend_kind = "local"

    def port(self):
        return self.cfg.port("scrapling")

    def url(self):
        return None      # MCP endpoint, not a web page -> no "open" button

    def build(self):
        host = self.cfg.host()
        args = ["mcp", "--http", "--host", host, "--port", str(self.port())]
        env = self._env()
        if host in ("127.0.0.1", "localhost", "::1"):
            args.append("--no-auth")                        # loopback only
        else:
            tok = self._dir() / "mcp_token.txt"             # LAN: token required (created by the installer)
            env["SCRAPLING_MCP_AUTH_TOKEN"] = tok.read_text(encoding="utf-8").strip() if tok.is_file() else ""
        return StartSpec(self._cli(*args), cwd=str(self._dir()), env=env)


class ScraplingShellModule(_ScraplingBase):
    """Interactive Scrapling console (IPython) in its own window."""
    id = "scrapling-shell"
    name = "Scrapling Shell"
    interactive = True
    _backend_kind = "local"

    def build(self):
        return StartSpec(self._cli("shell"), cwd=str(self._dir()), env=self._env())


class BatModule(Module):
    """A launcher script (e.g. AI_CLI\\Claude.bat) without a port.

    Backend kind is dynamic (see core/provider.py): by default all five CLI tools
    (Claude/Codex/Copilot/Antigravity/Happy) talk to a remote provider's cloud API - none of
    them run a local model themselves (that's Ollama/llama.cpp/ComfyUI). But a profile can be
    switched to "local" in the Dashboard (click the badge), which routes that CLI's traffic to
    whichever local server (llama.cpp preferred, else Ollama) is actually running right now."""

    interactive = True
    _backend_kind = "api"      # static fallback for tools without a profile (e.g. Happy) - see backend_kind()

    def __init__(self, cfg: Config, bat: Path):
        super().__init__(cfg)
        self.bat = bat
        self.id = "cli:" + bat.stem
        self.name = bat.stem

    def _local_wanted(self) -> bool:
        cli = self.bat.stem
        return profiles.supported(cli) and provider.get_provider(self.cfg, profiles.selected(self.cfg, cli)) == "local"

    def backend_kind(self) -> str:
        """Drives the Dashboard badge, refreshed every second from the UI thread (refresh()) - must
        never block, so it reads the cache StatusPoller warms in the background instead of probing
        the local server's TCP port itself (see provider.cached_local_source())."""
        if not self._local_wanted():
            return "api"
        return "local" if provider.cached_local_source() else "local-off"

    def check(self):
        return (True, "ready") if self.bat.exists() else (False, "missing")

    def build(self):
        # extra arguments: --profile <name> (skips the Node profile menu) + MCP servers ticked for this CLI;
        # the Node launcher forwards everything it does not know to the tool itself
        args = [*profiles.cli_args(self.cfg, self.bat.stem), *mcp.cli_args(self.cfg, self.bat.stem)]
        env = {}
        if self._local_wanted():
            src = provider.local_source(self.cfg)
            if src is not None:
                _label, url = src
                env = provider.env_override(self.bat.stem, url)
                # Copilot/Antigravity: no confirmed override mechanism (see provider.UNVERIFIED_TOOLS) -
                # env stays empty for them, the tool starts exactly as before against its own cloud API.
        return StartSpec([str(self.bat), *args], cwd=str(self.bat.parent), env=env)


class CustomModule(Module):
    def __init__(self, cfg: Config, entry: dict):
        super().__init__(cfg)
        self.entry = entry
        self.id = "custom:" + entry["id"]
        self.name = entry.get("name", entry["id"])

    def port(self):
        return self.entry.get("port")

    def url(self):
        return self.entry.get("url")

    @property
    def health_path(self):           # optional "health": "/path" in config.json -> custom_tools
        return self.entry.get("health")

    def backend_kind(self) -> str:
        # Optional "backend": "local"|"api"|"cloud" in config.json -> custom_tools; unset = no badge
        return self.entry.get("backend", "")

    def check(self):
        cmd = self.cfg.expand(self.entry["command"][0])
        return (True, "ready") if os.path.exists(cmd) else (False, f"not found: {cmd}")

    def build(self):
        cmd = [self.cfg.expand(c) if "{ROOT}" in c else c for c in self.entry["command"]]
        cwd = self.cfg.expand(self.entry["cwd"]) if self.entry.get("cwd") else None
        return StartSpec(cmd, cwd=cwd)


class ExternalModule(Module):
    """A service that is always running elsewhere (e.g. OpenWebUI on the Home Assistant server)."""
    external = True

    def __init__(self, cfg: Config, entry: dict):
        super().__init__(cfg)
        self.entry = entry
        self.id = "external:" + entry["id"]
        self.name = entry.get("name", entry["id"])
        u = urlparse(entry["url"])
        self.host = u.hostname or "127.0.0.1"
        self._port = u.port or (443 if u.scheme == "https" else 80)

    def port(self):
        return self._port

    def url(self):
        return self.entry["url"]

    def backend_kind(self) -> str:
        # Optional "backend": "local"|"api"|"cloud" in config.json -> external_services;
        # defaults to "cloud" - "runs elsewhere, reachable over the network" is the definition
        # of this module, e.g. OpenWebUI on the Home Assistant server (LAN, not this PC).
        return self.entry.get("backend", "cloud")

    def check(self):
        return True, "external"


def discover_modules(cfg: Config) -> list[Module]:
    mods: list[Module] = [ComfyUIModule(cfg), OllamaModule(cfg), LlamaCppModule(cfg),
                          ScraplingMcpModule(cfg), ScraplingShellModule(cfg)]
    cli = cfg.path("cli")
    if cli.is_dir():
        mods += [BatModule(cfg, b) for b in sorted(cli.glob("*.bat"))]
    mods += [CustomModule(cfg, e) for e in cfg.data.get("custom_tools", [])]
    mods += [ExternalModule(cfg, e) for e in cfg.data.get("external_services", [])]
    return mods
